Analytic imf
ArtificialStellarPopulations/ArtPop pull request #6
Opened 2021-12-01 16:27 UTC by tbmiller-astro

Updated implementation of imf integration to be completely analytic, which is much faster.  Functionality should be identical and you can now use custom (broken) power law IMFs.

2021-12-11 15:00 UTC, johnnygreco requested changes
Thanks so much, Tim! 

Most of my requests are to update the formatting to be more consistent with the rest of the code.  Please make sure the unit tests still pass after the updates. Let me know if have any questions / thoughts!

2021-12-13 16:16 UTC, tbmiller-astro commented on src/artpop/stars/imf.py
> +        norm_mass_min=None, norm_mass_max=None):
Added these in the latest commit!

2021-12-13 16:17 UTC, tbmiller-astro commented on src/artpop/stars/imf.py
> +            return (m**(a0+1.) - self.eval_min**(a0+1.))/(a0+1)/c0
Changed to single `return` statement.

2021-12-13 16:18 UTC, tbmiller-astro commented on src/artpop/stars/isochrones.py
> +            Stellar Initial mass function, see imf.py for details
Added additional info here and in other functions in isochrones.py and populations.py

2021-12-13 16:18 UTC, tbmiller-astro commented on src/artpop/stars/imf.py
> +    prop : str or dict
Change the name of all these from `prop` to `params`

2021-12-13 16:19 UTC, tbmiller-astro commented on src/artpop/stars/imf.py
> +        should not need to change this.
I agree, changed it to be hard coded

2021-12-13 16:20 UTC, tbmiller-astro commented on src/artpop/stars/imf.py
> +salpeter_prop = {'a':[-2.35]*3,'b':[2e2,3e2]}
Added a check in the initialization of the class to check for this. So now can pass a float for a single power law

2022-01-23 19:50 UTC, johnnygreco approved these changes
Assume work – thanks Tim!

2022-01-23 19:50 UTC, merged